#!/bin/bash
echo "=== MindMate Team Setup ==="
echo ""
echo "1. Clone repository:"
echo "   git clone https://github.com/Freddiecoder99/mindmate-harmony-space.git"
echo "   cd mindmate-harmony-space"
echo ""
echo "2. Checkout development branch:"
echo "   git checkout development"
echo ""
echo "3. Install dependencies:"
echo "   pip install -r requirements.txt"
echo ""
echo "4. Test ByLLM demo:"
echo "   jsctl jac run jac/byllm_demo.jac"
echo ""
echo "5. Explore files:"
echo "   ls jac/byllm_*.jac"
echo "   ls frontend/"
echo ""
echo "6. Check README:"
echo "   https://github.com/Freddiecoder99/mindmate-harmony-space#readme"
